Attribute VB_Name = "Variables"

Public a As Integer
Public Alpha As Double
Public Ants As Integer
Public Assigned() As Boolean
Public BaCapUsed() As Double
Public BaCovered() As Double
Public Beta As Double
Public Best_Solution() As Double
Public CapUsed() As Integer
Public Capv As Integer
Public Chosen As Integer
Public Covered_Distance() As Double
Public Ctrl() As Integer
Public Delta_Tao() As Double
Public Demand() As Integer
Public Distance() As Double
Public Eta() As Double
Public g As Integer
Public Generations As Integer
Public i As Integer
Public MaxNv As Integer
Public MinX As Double
Public MaxX As Double
Public MinY As Double
Public MaxY As Double
Public Nodes As Integer
Public NNodes As Integer
Public Nv As Integer
Public Objective_Function() As Double
Public Probability As Double
Public Problem As String
Public Rho As Double
Public Route() As Integer
Public Solution() As Double
Public Sum As Double
Public Summary() As Integer
Public Tao() As Double
Public TimeC As Single
Public X() As Double
Public Y() As Double

